Db
awave1/fitness-tracker pull request #2
Opened 2018-10-23 02:06 UTC by dartuso

Implemented Entities from Relational Model in android room database format.
Still need to do some foreign keys, and review primary key tags.

2018-10-23 02:31 UTC, awave1 requested changes
looks good, just gotta fix the formatting (need to use CamelCase)

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/BodyMeasure_Recording.java
> +public class BodyMeasure_Recording {
```suggestion
public class BodyMeasureRecording {
```

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/BodyMeasure_Recording.java
> +    public int recording_id;
```suggestion
    public int recordingId;
```

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/Goal.java
> +    public String goal_description;
```suggestion
    public String goalDescription;
```

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/Goal.java
> +    public Date completion_date;
```suggestion
    public Date completionDate;
```

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/History.java
> +    public int user_id;
```suggestion
    public int userId;
```

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/History.java
> +    public int workout_id;
```suggestion
    public int workoutId;
```

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/Micronutrient_Recording.java
> +public class Micronutrient_Recording {
```suggestion
public class MicronutrientRecording {
```

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/Micronutrient_Recording.java
> +    public int recording_id;
```suggestion
    public int recordingId;
```

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/Micronutrient_Recording.java
> +class micronutrient {
?? why lowercase
```suggestion
class Micronutrient {
```

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/Nutrition_Recording.java
> +public class Nutrition_Recording {
```suggestion
public class NutritionRecording {
```

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/Nutrition_Recording.java
> +    public int recording_id;
```suggestion
    public int recordingId;
```

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/Nutrition_Recording.java
> +class macronutrient {
same here
```suggestion
class Macronutrient {
```

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/Records.java
> +    public String user_id;
```suggestion
    public String userId;
```

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/Records.java
> +    public String record_id;
```suggestion
    public String recordId;
```

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/Schedule.java
> +    public int workout_id;
```suggestion
    public int workoutId;
```

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/Schedule.java
> +    public int trainer_id;
```suggestion
    public int trainerId;
```

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/Schedule.java
> +    public int user_id;
```suggestion
    public int userId;
```

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/Schedule.java
> +    public int recording_id;
```suggestion
    public int recordingId;
```

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/Set_Exercise.java
> +public class Set_Exercise {
```suggestion
public class SetExercise {
```

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/Set_Exercise.java
> +    public int workout_id;
```suggestion
    public int workoutId;
```

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/Timed_Exercise.java
> +public class Timed_Exercise {
```suggestion
public class TimedExercise {
```

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/Timed_Exercise.java
> +    public int workout_id;
```suggestion
    public int workoutId;
```

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/Trainer.java
> +    public String trainer_id;
```suggestion
    public String trainerId;
```

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/Trains.java
> +    public int trainer_id;
```suggestion
    public int trainerId;
```

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/Trains.java
> +    public int user_id;
```suggestion
    public int userId;
```

2018-10-23 02:31 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/Workout.java
> +    public int workout_id;
```suggestion
    public int workoutId;
```

2018-10-23 18:38 UTC, awave1 approved these changes

2018-10-23 19:19 UTC, dartuso commented
Thank u mr project manager

2018-10-31 22:26 UTC, awave1 requested changes

2018-10-31 22:26 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/BodyMeasureRecording.java
> +    public String Bodypart;
```suggestion
    public String bodypart;
```

2018-10-31 22:26 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/BodyMeasureRecording.java
> +    public double Bodypart_size;
```suggestion
    public double bodypartSize;
```

2018-10-31 23:01 UTC, awave1 approved these changes

2018-10-31 23:01 UTC, awave1 commented on app/src/main/java/com/group15/fitnesstracker/db/User.java
> +    public float weight;
```suggestion
    public double weight;
```

2018-10-31 23:08 UTC, merged